// Import des fichiers de style globaux
import "@/styles/globals.css";
import "@/styles/global-ui-enhancements.css";
import "@/styles/mobile-light-mode-fixes.css"; // Importation des correctifs pour le mode clair sur mobile
import "@/styles/critical-light-mode-fixes.css"; // Ajout des correctifs critiques pour le mode clair
import "@/styles/dashboard-light-mode-fixes.css"; // Correctifs spécifiques pour le Dashboard en mode clair
import "@/styles/dashboard-dark-mode-fixes.css"; // Préservation du Dashboard en mode sombre
import "@/components/Calendar.css"; // Correctifs spécifiques pour le composant Calendar
import "@/components/DashboardTab.css"; // Correctifs spécifiques pour les icônes du dashboard
import "@/components/ui-dark-mode-fixes.css"; // Correctifs globaux pour les icônes en mode sombre
import "@/components/dashboard-icons-fixes.css"; // Correctifs spécifiques pour les icônes problématiques

import { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { Providers } from "./providers";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased", inter.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
